export const LIST_ALL = 'LIST_ALL'; 
export const ADD_TASK='ADD_TASK';
export const SET_PAGINATION_NEXT='SET_PAGINATION_NEXT';
export const SET_PAGINATION_PREVIOUS='SET_PAGINATION_PREVIOUS';
export const CHOOSE_ITEM_PAGINATION='CHOOSE_ITEM_PAGINATION';
export const CHOOSE_ITEM_CITY='CHOOSE_ITEM_CITY';
export const FILTER_ITEM_CITY='FILTER_ITEM_CITY';